version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    image: react-flask-app-api
    container_name: flask-api
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  client:
    build:
      context: ./pptx-to-notes
      dockerfile: Dockerfile.client
    image: react-flask-app-client
    container_name: react_client
    ports: 
      - "3000:80"