FROM node:16-alpine as build-step
WORKDIR /pptx-to-notes
ENV PATH /pptx-to-notes/node_modules/.bin:$PATH
COPY package.json ./
#COPY yarn.lock ./
COPY ./src ./src
COPY ./public ./public
RUN yarn install
RUN yarn build

FROM nginx:stable-alpine
COPY --from=build-step /pptx-to-notes/build /usr/share/nginx/html
COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf